/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg7_kennethnuñez;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Burni
 */
public class LabGUI extends javax.swing.JFrame {

    /**
     * Creates new form LabGUI
     */
    public LabGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        CarName = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        PiezaName = new java.awt.TextField();
        PiezaMaterial = new java.awt.TextField();
        PiezaTime = new java.awt.TextField();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        FatherComboBoxModel = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarPiezas = new javax.swing.JTree();
        NoFatherCb = new javax.swing.JComboBox<>();
        label5 = new java.awt.Label();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MainTabStateChanged(evt);
            }
        });

        label1.setText("Nombre del Carro");

        jButton1.setText("Crear Carro");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        label2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        label2.setText("Pieza");

        label3.setText("Nombre");

        label4.setText("Material");

        label6.setText("Tiempo");

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("Padre");

        jButton2.setText("Crear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PiezaName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PiezaMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PiezaTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FatherComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(81, 81, 81))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CarName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FatherComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PiezaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PiezaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PiezaTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        MainTab.addTab("Creacion de Vehiculo", jPanel1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Ensamblaje");
        CarPiezas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(CarPiezas);

        label5.setText("Carro");

        button1.setLabel("Generate Tree Design");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NoFatherCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoFatherCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainTab.addTab("Ensamblaje", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTab, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        Carro nuevo = new Carro(CarName.getText());
        if (Contains(nuevo)) {
            JOptionPane.showMessageDialog(this, "Ya existe el carro.");
        } else {
            todo.add(nuevo);
            DefaultComboBoxModel model = new DefaultComboBoxModel(todo.toArray());
            FatherComboBoxModel.setModel(model);
        }
        CarName.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    public boolean Contains(Carro toTest) {
        boolean container = false;
        for (int i = 0; i < todo.size(); i++) {
            if (todo.get(i) instanceof Carro) {
                if (((Carro) todo.get(i)).getNombre().equals(toTest.getNombre())) {
                    container = true;
                }

            }
        }
        return container;
    }

    public boolean Contains(Piezas toTest) {
        boolean container = false;
        for (int i = 0; i < todo.size(); i++) {
            if (todo.get(i) instanceof Piezas) {
                if (((Piezas) todo.get(i)).getNombre().equals(toTest.getNombre())) {
                    container = true;
                }

            }
        }
        return container;
    }
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if (FatherComboBoxModel.getSelectedIndex() >= 0) {
            try {
                String Pnombre = PiezaName.getText();
                String Pmaterial = PiezaMaterial.getText();
                int Ptiempo = Integer.parseInt(PiezaTime.getText());
                Piezas nueva = new Piezas(Pnombre, Pmaterial, Ptiempo);
                if (Contains(nueva)) {
                    JOptionPane.showMessageDialog(this, "Ya existe la pieza. ");
                } else {
                    Object temporal = FatherComboBoxModel.getSelectedItem();
                    if (temporal instanceof Carro) {
                        ((Carro) temporal).getPieces().add(nueva);
                    } else {
                        ((Piezas) temporal).getPieces().add(nueva);
                    }
                    nueva.setPadre(temporal);
                    todo.add(nueva);
                    DefaultComboBoxModel model = new DefaultComboBoxModel(todo.toArray());
                    FatherComboBoxModel.setModel(model);
                    PiezaName.setText("");
                    PiezaMaterial.setText("");
                    PiezaTime.setText("");
                    FatherComboBoxModel.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(this, "Se ha agregado exitosamente.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ingrese un tiempo como numeros enteros.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado un padre.");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void MainTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MainTabStateChanged
        // TODO add your handling code here:
        if (MainTab.getSelectedIndex() == 1) {
            cars.clear();
            for (int i = 0; i < todo.size(); i++) {
                if (todo.get(i) instanceof Carro) {
                    cars.add((Carro) todo.get(i));
                }
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(cars.toArray());
            NoFatherCb.setModel(model);
            //Necesito un metodo que Recorra el ArrayList todo y me determine de quien es hijo o si es padre.
            /*DefaultTreeModel modelo = (DefaultTreeModel) CarPiezas.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
            raiz.removeAllChildren();
            for (int i = 0; i < todo.size(); i++) {
                if(todo.get(i) instanceof Carro){
                    DefaultMutableTreeNode car = new DefaultMutableTreeNode(todo.get(i));
                    //raiz.add(car);
                    
                    for (int j = 0; j < ((Carro)todo.get(i)).getPieces().size(); j++) {
                        DefaultMutableTreeNode temp = recursiva(((Carro)todo.get(i)).getPieces().get(j), car); 
                        car.add(temp);
                    }
                    raiz.add(car);
                }
            }

            modelo.reload();*/
        }
    }//GEN-LAST:event_MainTabStateChanged

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        if (NoFatherCb.getSelectedIndex() >= 0) {
            DefaultTreeModel modelo = (DefaultTreeModel) CarPiezas.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
            raiz.removeAllChildren();;
            Carro x = (Carro) NoFatherCb.getSelectedItem();
            
            for (int i = 0; i < todo.size(); i++) {
                if (todo.get(i) instanceof Carro) {
                    if (((Carro) todo.get(i)).getNombre().equals(x.getNombre())) {
                        DefaultMutableTreeNode carro = new DefaultMutableTreeNode(((Carro) todo.get(i)));
                        for (int j = 0; j < ((Carro) todo.get(i)).getPieces().size(); j++) {
                            DefaultMutableTreeNode temp = recursiva(((Carro) todo.get(i)).getPieces().get(j), raiz);
                            carro.add(temp);
                        }
                        raiz.add(carro);
                    }
                }
            }
            modelo.reload();
            
        } else {
            JOptionPane.showMessageDialog(this, "Usted no ha seleccionado ningun objeto. ");
        }
    }//GEN-LAST:event_button1MouseClicked

    public DefaultMutableTreeNode recursiva(Piezas yet, DefaultMutableTreeNode zeta) {
        if (yet.getPieces().size() == 0) {
            DefaultMutableTreeNode xet = new DefaultMutableTreeNode(yet);
            return xet;
        } else {
            DefaultMutableTreeNode xetter = new DefaultMutableTreeNode(yet);
            for (int i = 0; i < yet.getPieces().size(); i++) {
                xetter.add(recursiva(yet.getPieces().get(i), xetter));
            }
            return xetter;
        }
    }

    public boolean HasHizos(Piezas z) {
        boolean pertenece = false;
        for (int i = 0; i < todo.size(); i++) {
            if (todo.get(i) instanceof Piezas) {
                Object x = ((Piezas) (todo.get(i))).getPadre();
                x.toString().equals(z.toString());
                pertenece = true;
            }
        }
        return pertenece;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabGUI().setVisible(true);
            }
        });
    }
    static ArrayList todo = new ArrayList();
    static DefaultMutableTreeNode hijos;
    static ArrayList<Carro> cars = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField CarName;
    private javax.swing.JTree CarPiezas;
    private javax.swing.JComboBox<String> FatherComboBoxModel;
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JComboBox<String> NoFatherCb;
    private java.awt.TextField PiezaMaterial;
    private java.awt.TextField PiezaName;
    private java.awt.TextField PiezaTime;
    private java.awt.Button button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables
}
